version: "3.4"

services:

  telegraf:
    image: tomochain/infra-telegraf:devnet
    hostname: sun
    environment:
      METRICS_ENDPOINT: https://metrics.devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  masternode_sun:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      BOOTNODES: enode://ad365c2e74ded1b878b974c4387f49dc9fa7694af13339e6720a035fb65d7a815b33502ae5232a5cbccd4c39ee6908f026fe41b808bf81c628bfd00078beb2ac@52.77.194.164:30301,enode://bdbbd98355eab4e23dc5d7b8193f5469247b1f6df3a007fee39a683a58e3ceec519e10a8cf0334df91c7cb2dd63beedac938e46c1433d95bfff4f3ee8ee24914@13.228.93.232:30301,enode://a879992bb4315aec4b8ade7b4d8c5569f08d44028c99a299b370270093d10a395b50c82429240beb7ce4c14bb7d3532215d457006e11aa7788379aa815a475dc@18.136.42.72:30301
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - sun:/tomochain/data

secrets:
  tomochain_password_sun:
    external: true
  tomochain_pk_sun:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  sun:
