version: "3.4"

services:

  masternode_sun:
    image: tomo-node:latest
    environment:
      IDENTITY: sun
      IS_BOOTNODE: "true"
      INDEX: "1"
    volumes:
      - sun:/node/data
      - bootnodes:/node/bootnodes
      - ./password:/node/password:ro
  masternode_moon:
    image: tomo-node:latest
    environment:
      IDENTITY: moon
      IS_BOOTNODE: "false"
      INDEX: "2"
    volumes:
      - moon:/node/data
      - bootnodes:/node/bootnodes:ro
      - ./password:/node/password:ro
  masternode_earth:
    image: tomo-node:latest
    environment:
      IDENTITY: earth
      IS_BOOTNODE: "false"
      INDEX: "3"
    volumes:
      - earth:/node/data
      - bootnodes:/node/bootnodes:ro
      - ./password:/node/password:ro

  influxdb:
    image: tomochain/influxdb:devnet
    volumes:
      - influxdb:/var/lib/influxdb

  telegraf:
    image: tomochain/telegraf:devnet
    hostname: devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    depends_on:
      - influxdb

  grafana:
    image: tomochain/grafana:devnet
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  moon:
    name: moon
  sun:
    name: sun
  earth:
    name: earth
  bootnodes:
    name: bootnodes
  influxdb:
    name: influxdb
  grafana:
    name: grafana
