version: "3.4"

services:

  telegraf:
    image: tomochain/infra-telegraf:testnet
    hostname: changeme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    deploy:
      mode: global

  fullnode:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: changeme
      BOOTNODES: enode://4d3c2cc0ce7135c1778c6f1cfda623ab44b4b6db55289543d48ecfde7d7111fd420c42174a9f2fea511a04cf6eac4ec69b4456bfaaae0e5bd236107d3172b013@52.221.28.223:30301,enode://298780104303fcdb37a84c5702ebd9ec660971629f68a933fd91f7350c54eea0e294b0857f1fd2e8dba2869fcc36b83e6de553c386cf4ff26f19672955d9f312@13.251.101.216:30301,enode://46dba3a8721c589bede3c134d755eb1a38ae7c5a4c69249b8317c55adc8d46a369f98b06514ecec4b4ff150712085176818d18f59a9e6311a52dbe68cff5b2ae@13.250.94.232:30301
      NETSTATS_HOST: stats.testnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET: anna-coal-flee-carrie-zip-hhhh-tarry-laue-felon-rhine
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
    volumes:
      - blockchain:/tomochain/data

volumes:
  blockchain:
