{
 "title": "Docker",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hosts:",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\""
   },
   {
    "name": "containers",
    "label": "Containers:",
    "query": "SHOW TAG VALUES WITH KEY = \"container_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage per container",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "alias": "[ [[tag_engine_host]] ] [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage per container",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory usage" }
   ],
   "targets": [
    {
     "alias": "[ [[tag_engine_host]] ] [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$containers$/" }
     ]
    },
    {
     "alias": "[ [[tag_engine_host]] ] [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - Downstream",
   "type": "graph",
   "description": "Downstream network usage per container",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Downstream" }
   ],
   "targets": [
    {
     "alias": "[ [[tag_engine_host]] ] [[tag_container_name]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - Upstream",
   "type": "graph",
   "description": "Upstream network usage per container",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "Upstream" }
   ],
   "targets": [
    {
     "alias": "[ [[tag_engine_host]] ] [[tag_container_name]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$containers$/" }
     ]
    }
   ]
  }
 ]
}