logLevel = "DEBUG"
debug = true

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/run/secrets/proxy_cert_pem"
      keyFile = "/run/secrets/proxy_cert_private_key"

[file]

[backends]
  [backends.backendStats]
    [backends.backendStats.servers.server1]
    url = "http://netstats-server:3000"
  [backends.backendMaster]
    [backends.backendMaster.servers.server1]
    url = "http://tomomaster:3001"
  [backends.backendScan]
    [backends.backendScan.servers.server1]
    url = "http://tomoscan-client:3000"
  [backends.backendGrafana]
    [backends.backendGrafana.servers.server1]
    url = "http://grafana:3000"

[frontends]
  [frontends.stats]
  backend = "backendStats"
    [frontends.stats.routes.test_1]
    rule = "Host:stats.devnet.tomochain.com"
  [frontends.master]
  backend = "backendMaster"
    [frontends.master.routes.test_2]
    rule = "Host:master.devnet.tomochain.com"
  [frontends.scan]
  backend = "backendScan"
    [frontends.scan.routes.test_3]
    rule = "Host:scan.devnet.tomochain.com"
  [frontends.grafana]
  backend = "backendGrafana"
    [frontends.grafana.routes.test_4]
    rule = "Host:grafana.devnet.tomochain.com"
