version: "3.4"

services:

  netapi-client_sun:
    image: netapi-client_sun
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: sun
    volumes:
      - ./ressources/app_sun.json:/netapi/app.json

  netapi-client_moon:
    image: netapi-client_moon
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: moon
    volumes:
      - ./ressources/app_moon.json:/netapi/app.json

  netapi-client_earth:
    image: netapi-client_earth
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: earth
    volumes:
      - ./ressources/app_earth.json:/netapi/app.json

  netapi-server:
    image: netapi-server
    build:
      context: ../eth-netstats
    environment:
      WS_SECRET: test
    ports:
      - "3000:3000"
