version: "3.4"

services:

  tomomaster:
    image: tomomaster
    build:
      context: ../tomomaster
    depends_on:
      - mongodb_master

  mongodb_master:
    image: mongo:3.6
    volumes:
      - "mongodb_master:/data/db"

  redis_master:
    image: redis:4-alpine

volumes:
  mongodb_master:
