version: "3.4"

services:

  tomochain_sun:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: sun
      IS_BOOTNODE: "true"
      INDEX: "1"
    volumes:
      - sun:/tomochain/data
      - bootnodes:/tomochain/bootnodes
      - genesis:/tomochain/genesis/:ro
      - keystore:/tomochain/keystore/:ro
      - ./ressources/password:/tomochain/password:ro
  netapi-client_sun:
    image: tomochain/infra-netapi-client:devnet
    environment:
      WS_SECRET: test
      INSTANCE_NAME: sun
    volumes:
      - ./ressources/app_sun.json:/netapi/app.json

  tomochain_moon:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: moon
      IS_BOOTNODE: "false"
      INDEX: "2"
    volumes:
      - moon:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro
      - genesis:/tomochain/genesis/:ro
      - keystore:/tomochain/keystore/:ro
      - ./ressources/password:/tomochain/password:ro
  netapi-client_moon:
    image: tomochain/infra-netapi-client:devnet
    environment:
      WS_SECRET: test
      INSTANCE_NAME: moon
    volumes:
      - ./ressources/app_moon.json:/netapi/app.json

  tomochain_earth:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: earth
      IS_BOOTNODE: "false"
      INDEX: "3"
    volumes:
      - earth:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro
      - genesis:/tomochain/genesis/:ro
      - keystore:/tomochain/keystore/:ro
      - ./ressources/password:/tomochain/password:ro
  netapi-client_earth:
    image: tomochain/infra-netapi-client:devnet
    environment:
      WS_SECRET: test
      INSTANCE_NAME: earth
    volumes:
      - ./ressources/app_earth.json:/netapi/app.json

  netapi-server:
    image: tomochain/infra-netapi-server:devnet
    environment:
      WS_SECRET: test
    ports:
      - "3000:3000"

  influxdb:
    image: tomochain/infra-influxdb:devnet
    volumes:
      - influxdb:/var/lib/influxdb
  telegraf:
    image: tomochain/infra-telegraf:devnet
    hostname: devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  grafana:
    image: tomochain/grafana:devnet
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3771:3000"

volumes:
  moon:
  sun:
  earth:
  bootnodes:
  influxdb:
  grafana:
  genesis:
    external: true
  keystore:
    external: true
