version: "3.4"

services:

  tomochain_sun:
    image: tomochain_sun
    build:
      context: ../tomochain
    environment:
      IDENTITY: sun
      IS_BOOTNODE: "true"
    secrets:
      - password_sun
      - key_sun
    volumes:
      - sun:/tomochain/data
      - bootnodes:/tomochain/bootnodes
      - ./ressources/password:/tomochain/password:ro

  tomochain_moon:
    image: tomochain_moon
    build:
      context: ../tomochain
    environment:
      IDENTITY: moon
    secrets:
      - password_moon
      - key_moon
    volumes:
      - moon:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro
      - ./ressources/password:/tomochain/password:ro

  tomochain_earth:
    image: tomochain_earth
    build:
      context: ../tomochain
    environment:
      IDENTITY: earth
    secrets:
      - password_earth
      - key_earth
    volumes:
      - earth:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro
      - ./ressources/password:/tomochain/password:ro

volumes:
  moon:
  sun:
  earth:
  bootnodes:

secrets:
  password_sun:
    file: ./secrets/password_sun.secret
  key_sun:
    file: ./secrets/key_sun.secret
  password_moon:
    file: ./secrets/password_moon.secret
  key_moon:
    file: ./secrets/key_moon.secret
  password_earth:
    file: ./secrets/password_earth.secret
  key_earth:
    file: ./secrets/key_earth.secret
