version: "3.4"

services:

  tomomaster:
    image: tomomaster
    build:
      context: ../tomomaster
    secrets:
      - mnemonic_tomomaster
    depends_on:
      - mongodb_master

  mongodb_master:
    image: mongo:3.6

  redis_master:
    image: redis:4-alpine

secrets:
  mnemonic_tomomaster:
    file: ./secrets/mnemonic_tomomaster.secret
