version: "3.4"

services:

  tomoscan-client:
    image: tomoscan-client
    build:
      context: ../tomoscan-client
    depends_on:
      - tomoscan-server

  tomoscan-server:
    image: tomoscan-server
    build:
      context: ../tomoscan-server
    environment:
     - MONGODB_URI=mongodb://mongodb_scan:27017/explorer
    depends_on:
     - mongodb_scan

  mongodb_scan:
    image: mongo:3.6
    volumes:
      - "mongodb_scan:/data/db"

volumes:
  mongodb_scan:
