version: "3.4"

services:

  influxdb:
    image: influxdb
    build:
      context: ../influxdb
    environment:
      - influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf
    build:
      context: ../telegraf
    hostname: localnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  grafana:
    image: grafana
    build:
      context: ../grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3771:3000"

volumes:
  influxdb:
  grafana:
