version: "3.4"

services:

  nginx_master:
    image: nginx:1.15-alpine
    volumes:
      - ./app.template:/etc/nginx/conf.d/default.conf
      - ./nginx.template:/etc/nginx/nginx.conf
      - ./certs:/certs
    depends_on:
      - tomomaster
    ports:
      - "80:80"
      - "443:443"

  tomomaster:
    image: tomochain/infra-tomomaster:latest
    depends_on:
      - mongodb_master

  mongodb_master:
    image: mongo:3.6
    volumes:
      - "mongodb_master:/data/db"

  redis_master:
    image: redis:4-alpine

volumes:
  mongodb_master:
