version: "3.4"

services:

  netstats-client_sun:
    image: netstats-client_sun
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: sun
    volumes:
      - ./ressources/app_sun.json:/netstats/app.json

  netstats-client_moon:
    image: netstats-client_moon
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: moon
    volumes:
      - ./ressources/app_moon.json:/netstats/app.json

  netstats-client_earth:
    image: netstats-client_earth
    build:
      context: ../ethereum-network-intelligence-api
    environment:
      WS_SECRET: test
      INSTANCE_NAME: earth
    volumes:
      - ./ressources/app_earth.json:/netstats/app.json

  netstats-server:
    image: netstats-server
    build:
      context: ../eth-netstats
    environment:
      WS_SECRET: test
    ports:
      - "3000:3000"
