version: "3.4"

services:

  influxdb:
    image: tomochain/infra-influxdb:devnet
    volumes:
      - influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf
    build:
      context: ../telegraf
    hostname: devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  grafana:
    image: tomochain/infra-grafana:devnet
    env_file:
      - config/metrics/grafana.env
    ports:
      - "3003:3000"
  postgres_grafana:
    image: postgres:10.4-alpine
    env_file:
      - config/metrics/postgres_grafana.env
    volumes:
      - postgres_grafana:/var/lib/postgresql/data

volumes:
  influxdb:
  postgres_grafana:
