version: "3.4"

services:

  influxdb:
    image: influxdb
    build:
      context: ../influxdb
    volumes:
      - influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf
    build:
      context: ../telegraf
    hostname: localnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
  grafana:
    image: grafana
    build:
      context: ../grafana
    environment:
      POSTGRES_PASSWORD: tomochain
      GF_DATABASE_HOST: postgres_grafana
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: tomochain
    ports:
      - "3003:3000"
  postgres_grafana:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: grafana
      POSTGRES_PASSWORD: tomochain
    volumes:
      - postgres_grafana:/var/lib/postgresql/data

volumes:
  influxdb:
  postgres_grafana:
