version: "3.4"

services:

  netstats-server:
    image: tomochain/infra-netstats-server:localnet
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret

secrets:
  netstats_ws_secret:
    external: true
