version: "3.4"

services:

  netstats-client_sun:
    image: tomochain/infra-netstats-client:devnet
    env_file:
      - config/netstats/netstats-client_sun.env
    volumes:
      - ./ressources/app_sun.json:/netstats/app.json

  netstats-client_moon:
    image: tomochain/infra-netstats-client:devnet
    env_file:
      - config/netstats/netstats-client_moon.env
    volumes:
      - ./ressources/app_moon.json:/netstats/app.json

  netstats-client_earth:
    image: tomochain/infra-netstats-client:devnet
    env_file:
      - config/netstats/netstats-client_earth.env
    volumes:
      - ./ressources/app_earth.json:/netstats/app.json

  netstats-server:
    image: tomochain/infra-netstats-server:devnet
    env_file:
      - config/netstats/netstats-server.env
    ports:
      - "3000:3000"
