version: "3.4"

services:

  netstats-client_sun:
    image: tomochain/infra-netstats-client:devnet
    environment:
      INSTANCE_NAME: sun
      RPC_HOST: 'tomochain_sun'
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret

  netstats-client_moon:
    image: tomochain/infra-netstats-client:devnet
    environment:
      INSTANCE_NAME: moon
      RPC_HOST: 'tomochain_moon'
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret

  netstats-client_earth:
    image: tomochain/infra-netstats-client:devnet
    environment:
      INSTANCE_NAME: earth
      RPC_HOST: 'tomochain_earth'
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret

  netstats-server:
    image: tomochain/infra-netstats-server:devnet
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret

secrets:
  netstats_ws_secret:
    external: true
