version: "3.4"

services:

  bootnode:
    image: bootnode:test
    tty: true
    volumes:
      - bootnodes:/tomochain/bootnodes

  masternode_sun:
    image: node:test
    tty: true
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      BOOTNODES_FILE: /tomochain/bootnodes/bootnodes
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - sun:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

  masternode_earth:
    image: node:test
    tty: true
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      BOOTNODES_FILE: /tomochain/bootnodes/bootnodes
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - earth:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

  masternode_moon:
    image: node:test
    tty: true
    environment:
      IDENTITY: moon
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
      BOOTNODES_FILE: /tomochain/bootnodes/bootnodes
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
      - netstats_ws_secret
    volumes:
      - moon:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

  node:
    image: node:test
    tty: true
    environment:
      BOOTNODES_FILE: /tomochain/bootnodes/bootnodes
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret
    volumes:
      - bootnodes:/tomochain/bootnodes:ro

secrets:
  tomochain_password_sun:
    external: true
  tomochain_password_moon:
    external: true
  tomochain_password_earth:
    external: true
  tomochain_pk_sun:
    external: true
  tomochain_pk_moon:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  moon:
  sun:
  earth:
