version: "3.4"

services:

  proxy:
    image: tomochain/infra-nginx:devnet
    ports:
      - 80:80
      - 443:443
      - 8545:8545
      - 8546:8546
    secrets:
      - proxy_cert_pem
      - proxy_cert_private_key

secrets:
  proxy_cert_pem:
    external: true
  proxy_cert_private_key:
    external: true
