version: "3.4"

services:

  proxy:
    image: tomochain/infra-gobetween:test
    secrets:
      - proxy_cert_pem
      - proxy_cert_private_key

secrets:
  proxy_cert_pem:
    external: true
  proxy_cert_private_key:
    external: true
