version: "3.4"

services:

  tomomaster:
    image: tomochain/infra-tomomaster:devnet
    ports:
      - "3001:3001"
    env_file:
      - config/tomomaster/tomomaster.env
    depends_on:
      - mongodb_master

  mongodb_master:
    image: mongo:3.6

  redis_master:
    image: redis:4-alpine
