version: "3.4"

services:

  tomoscan-client:
    image: tomochain/infra-tomoscan-client:devnet
    depends_on:
      - tomoscan-server

  tomoscan-server:
    image: tomochain/infra-tomoscan-server:devnet
    environment:
      MONGODB_URI: mongodb://mongodb_scan:27017/explorer
    depends_on:
     - mongodb_scan

  mongodb_scan:
    image: mongo:3.6
