version: "3.4"

services:

  tomoscan-client:
    image: tomochain/tomoscan-client:devnet
    depends_on:
      - tomoscan-server
      - redis_scan

  tomoscan-server:
    image: tomochain/tomoscan-server:devnet
    environment:
      MONGODB_URI: mongodb://mongodb_scan:27017/explorer
      REDIS_HOST: redis_scan
      CLIENT_URL: https://scan.devnet.tomochain.com/
      WEB3_URI: https://devnet.tomochain.com
    depends_on:
      - mongodb_scan
      - redis_scan

  tomoscan-crawler:
    image: tomochain/tomoscan-server:devnet
    command: run crawl
    environment:
      MONGODB_URI: mongodb://mongodb_scan:27017/explorer
      REDIS_HOST: redis_scan
    depends_on:
      - mongodb_scan
      - redis_scan

  mongodb_scan:
    image: mongo:3.6

  redis_scan:
    image: redis:4-alpine
