version: "3.4"

services:

  tomochain_sun:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: sun
      IS_BOOTNODE: true
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
    volumes:
      - sun:/tomochain/data
      - bootnodes:/tomochain/bootnodes

  tomochain_moon:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: moon
      IS_BOOTNODE: true
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
    volumes:
      - moon:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

  tomochain_earth:
    image: tomochain/infra-tomochain:devnet
    environment:
      IDENTITY: earth
      IS_BOOTNODE: true
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
    volumes:
      - earth:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

secrets:
  tomochain_password_sun:
    external: true
  tomochain_password_moon:
    external: true
  tomochain_password_earth:
    external: true
  tomochain_pk_sun:
    external: true
  tomochain_pk_moon:
    external: true
  tomochain_pk_earth:
    external: true

volumes:
  moon:
  sun:
  earth:
  bootnodes:
