version: "3.4"

services:

  tomoscan-client:
    image: tomochain/infra-tomoscan-client:localnet
    build:
      context: ../tomoscan-client
    ports:
      - "3002:3000"
    depends_on:
      - tomoscan-server

  tomoscan-server:
    image: tomochain/infra-tomoscan-server:localnet
    build:
      context: ../tomoscan-server
    environment:
      MONGODB_URI: mongodb://mongodb_scan:27017/explorer
    ports:
      - "3333:3333"
    depends_on:
      - mongodb_scan

  mongodb_scan:
    image: mongo:3.6
