version: "3.4"

services:

  tomomaster:
    image: tomochain/infra-tomomaster:devnet
    environment:
      MNEMONIC_FILE: /run/secrets/tomomaster_mnemonic
    secrets:
      - tomomaster_mnemonic
    depends_on:
      - mongodb_master

  mongodb_master:
    image: mongo:3.6

  redis_master:
    image: redis:4-alpine

secrets:
  tomomaster_mnemonic:
    external: true
