version: "3.4"

services:

  tomochain_sun:
    image: tomochain_sun
    tty: true
    build:
      context: ../tomochain
    ports:
      - 8545:8545
      - 30303:30303
    env_file:
      - config/tomochain/tomochain_sun.env
    volumes:
      - sun:/tomochain/data
      - bootnodes:/tomochain/bootnodes

  tomochain_moon:
    image: tomochain_moon
    tty: true
    build:
      context: ../tomochain
    env_file:
      - config/tomochain/tomochain_moon.env
    volumes:
      - moon:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

  tomochain_earth:
    image: tomochain_earth
    tty: true
    build:
      context: ../tomochain
    env_file:
      - config/tomochain/tomochain_earth.env
    volumes:
      - earth:/tomochain/data
      - bootnodes:/tomochain/bootnodes:ro

volumes:
  moon:
  sun:
  earth:
  bootnodes:
