{
 "title": "Docker services",
 "description": "Overview of the docker swarm state",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hosts:",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\""
   },
   {
    "name": "services",
    "label": "Services:",
    "query": "SHOW TAG VALUES WITH KEY = \"com.docker.swarm.service.name\" WHERE \"engine_host\" =~ /^$hosts$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Service containers",
   "type": "graph",
   "description": "Containers used by this service",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]] ([[tag_container_image]]:[[tag_container_version]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage.\n\nPercentage is per core. \n\nExample: A 4 cores CPU, can go up to 400%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "description": "RAM usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" }
     ]
    }
   ]
  },
  {
   "title": "Network uplink",
   "type": "graph",
   "description": "Network uplink usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" }
     ]
    }
   ]
  },
  {
   "title": "Network downlink",
   "type": "graph",
   "description": "Network downlink usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" }
     ]
    }
   ]
  }
 ]
}