version: "3.4"

services:

  masternode_tomochain01:
    image: tomochain/node:testnet
    environment:
      IDENTITY: TomoChain01
      PASSWORD_FILE: /run/secrets/tomochain_password_tomochain01
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_tomochain01
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_tomochain01
      - tomochain_pk_tomochain01
      - netstats_ws_secret
    volumes:
      - masternode-tomochain01:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == tomochain01

  masternode_tomochain02:
    image: tomochain/node:testnet
    environment:
      IDENTITY: TomoChain02
      PASSWORD_FILE: /run/secrets/tomochain_password_tomochain02
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_tomochain02
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_tomochain02
      - tomochain_pk_tomochain02
      - netstats_ws_secret
    volumes:
      - masternode-tomochain02:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == tomochain02

  masternode_tomochain03:
    image: tomochain/node:testnet
    environment:
      IDENTITY: TomoChain03
      PASSWORD_FILE: /run/secrets/tomochain_password_tomochain03
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_tomochain03
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_tomochain03
      - tomochain_pk_tomochain03
      - netstats_ws_secret
    volumes:
      - masternode-tomochain03:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.project == masternode
          - node.labels.masternode == tomochain03

secrets:
  tomochain_password_tomochain01:
    external: true
  tomochain_pk_tomochain01:
    external: true
  tomochain_password_tomochain02:
    external: true
  tomochain_pk_tomochain02:
    external: true
  tomochain_password_tomochain03:
    external: true
  tomochain_pk_tomochain03:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  masternode-tomochain01:
  masternode-tomochain02:
  masternode-tomochain03:
