version: "3.4"

services:

  netstats:
    image: tomochain/netstats:stable
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - 3000:3000
    secrets:
      - netstats_ws_secret
    deploy:
      placement:
        constraints:
          - node.labels.project == stats
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

secrets:
  netstats_ws_secret:
    external: true
