version: "3.4"

services:

  masternode_sun:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      BOOTNODES: 'enode://b4036537aa0cf0475b08495c5ebb8bd986664a246ae7f9b20dda7439606db9f81f0b83a99e170d5b3b13e9a812ce68ec8b285277d4bef375cd330c234b3d0b24@18.136.4.187:30301'
    ports:
      - 8545:8545
      - 8546:8546
      - 39393:39393
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - sun:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.masternode == sun

secrets:
  tomochain_password_sun:
    external: true
  tomochain_pk_sun:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  sun:
