version: "3.4"

services:

  netstats:
    image: tomochain/netstats:testnet
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  netstats_ws_secret:
    external: true
