version: "3.4"

services:

  tomomaster:
    image: tomochain/tomomaster:testnet
    environment:
      NODE_ENV: 'testnet'
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster_crawler:
    image: tomochain/tomomaster:testnet
    command: run crawl
    environment:
      NODE_ENV: 'testnet_crawler'
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster_db:
    image: mongo:3.6
    volumes:
      - tomomaster_data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  tomomaster_data:
