version: "3.4"

services:

  faucet:
    image: tomochain/faucet:testnet
    volumes:
      - ./config.json:/build/config.json
    deploy:
      placement:
        constraints:
          - node.role == manager
