version: "3.4"

services:

  proxy:
    image: tomochain/nginx:testnet
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - proxy_cert_pem
      - proxy_cert_private_key
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  proxy_cert_pem:
    external: true
  proxy_cert_private_key:
    external: true
