version: "3.4"

services:

  shepherd:
    image: mazzolino/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SLEEP_TIME: "5m"
    deploy:
      placement:
        constraints:
          - node.role == manager

  telegraf:
    image: tomochain/infra-telegraf:devnet
    hostname: earth.devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  masternode_earth:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      BOOTNODES: 'enode://b4036537aa0cf0475b08495c5ebb8bd986664a246ae7f9b20dda7439606db9f81f0b83a99e170d5b3b13e9a812ce68ec8b285277d4bef375cd330c234b3d0b24@18.136.4.187:30301'
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - earth:/tomochain/data

secrets:
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  earth:
