version: "3.4"

services:

  telegraf:
    image: tomochain/infra-telegraf:devnet
    hostname: bootnode.devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  bootnode:
    image: tomochain/infra-bootnode:devnet
    ports:
      - 30301:30301
