version: "3.4"

services:

  telegraf:
    image: tomochain/telegraf:testnet
    hostname: '{{.Node.Hostname}}'
    environment:
      METRICS_ENDPOINT: https://metrics.testnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    deploy:
      mode: global

  masternode_earth:
    image: tomochain/node:testnet
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      BOOTNODES: enode://4d3c2cc0ce7135c1778c6f1cfda623ab44b4b6db55289543d48ecfde7d7111fd420c42174a9f2fea511a04cf6eac4ec69b4456bfaaae0e5bd236107d3172b013@52.221.28.223:30301,enode://298780104303fcdb37a84c5702ebd9ec660971629f68a933fd91f7350c54eea0e294b0857f1fd2e8dba2869fcc36b83e6de553c386cf4ff26f19672955d9f312@13.251.101.216:30301,enode://46dba3a8721c589bede3c134d755eb1a38ae7c5a4c69249b8317c55adc8d46a369f98b06514ecec4b4ff150712085176818d18f59a9e6311a52dbe68cff5b2ae@13.250.94.232:30301
      VERBOSITY: 2
      NETSTATS_HOST: stats.testnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: 'true'
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - earth:/tomochain/data

secrets:
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  earth:
