version: "3.4"

services:

  bootnode:
    image: tomochain/infra-bootnode:devnet
    volumes:
      - bootnode:/tomochain
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  bootnode:
