version: "3.4"

services:

  netstats-server:
    image: tomochain/infra-netstats-server:devnet
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster:
    image: tomochain/tomomaster:latest
    environment:
      BC_RPC: 'http://masternode_moon:8545'
      EXPLORER_URL: 'https://scan.testnet.tomochain.com'
      DB_URI: 'mongodb://tomomaster_db:27017/governance'
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster_crawler:
    image: tomochain/tomomaster:latest
    command: run crawl
    environment:
      BC_RPC: 'https://testnet.tomochain.com'
      DB_URI: 'mongodb://tomomaster_db:27017/governance'
      REDIS_HOST: 'tomomaster_redis'
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomoscan:
    image: tomochain/tomoscan-client:latest
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomoscan_server:
    image: tomochain/tomoscan-server:latest
    environment:
      MONGODB_URI: mongodb://tomoscan_db:27017/explorer
      REDIS_HOST: tomoscan_redis
      CLIENT_URL: https://scan.testnet.tomochain.com/
      WEB3_URI: https://testnet.tomochain.com
      JWT_SECRET_FILE: /run/secrets/scan_jwt_secret
      APP_SECRET_FILE: /run/secrets/scan_app_secret
      SENDGRID_API_KEY_FILE: /run/secrets/sendgrid_api_key
    secrets:
      - scan_jwt_secret
      - scan_app_secret
      - sendgrid_api_key
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomoscan_crawler:
    image: tomochain/tomoscan-server:latest
    command: run crawl
    environment:
      MONGODB_URI: mongodb://tomoscan_db:27017/explorer
      REDIS_HOST: tomoscan_redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster_db:
    image: mongo:3.6
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomomaster_redis:
    image: redis:4-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomoscan_db:
    image: mongo:3.6
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomoscan_redis:
    image: redis:4-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  netstats_ws_secret:
    external: true
  sendgrid_api_key:
    external: true
  scan_jwt_secret:
    external: true
  scan_app_secret:
    external: true
