version: "3.4"

services:

  proxy:
    image: tomochain/infra-nginx:testnet
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 30304:30303
      - 30304:30303/udp
      - 30305:30303
      - 30305:30303/udp
      - 443:443
    secrets:
      - proxy_cert_pem
      - proxy_cert_private_key
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  proxy_cert_pem:
    external: true
  proxy_cert_private_key:
    external: true
