version: "3.4"

services:

  telegraf:
    image: tomochain/infra-telegraf:testnet
    hostname: changeme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    deploy:
      mode: global

  fullnode:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: changeme
      BOOTNODES: enode://9f3a7071bdd0f897c35e06118767dc2e060e8cf005679b06541a3e1c71cd3f757d53f0806db33917f14aa25fa0ab56da12351aba6b530280c43b144a0b97e789@18.136.151.139:30303
      NETSTATS_HOST: stats.testnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET: changeme
    volumes:
      - blockchain:/tomochain/data

volumes:
  blockchain:
