version: "3.4"

services:

  bootnode-sun:
    image: tomochain/bootnode:testnet
    volumes:
      - bootnode:/tomochain
    ports:
      - target: 30301
        published: 30301
        protocol: tcp
        mode: host
      - target: 30301
        published: 30301
        protocol: udp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager

  bootnode-moon:
    image: tomochain/bootnode:testnet
    volumes:
      - bootnode:/tomochain
    ports:
      - target: 30301
        published: 30301
        protocol: tcp
        mode: host
      - target: 30301
        published: 30301
        protocol: udp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager

  bootnode-earth:
    image: tomochain/bootnode:testnet
    volumes:
      - bootnode:/tomochain
    ports:
      - target: 30301
        published: 30301
        protocol: tcp
        mode: host
      - target: 30301
        published: 30301
        protocol: udp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  bootnode-sun:
  bootnode-moon:
  bootnode-earth:
