version: "3.4"

services:

  bootnode:
    image: tomochain/bootnode:testnet
    volumes:
      - bootnode:/tomochain
    ports:
      - target: 30301
        published: 30301
        protocol: tcp
        mode: host
      - target: 30301
        published: 30301
        protocol: udp
        mode: host
    deploy:
      replicas: 3
      placement:
        constraints:
          - engine.labels.type == masternode
          - node.hostname == sun.devnet.tomochain.com

volumes:
  bootnode:
