version: "3.4"

services:

  masternode_sun:
    image: tomochain/node:devnet
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: true
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - masternode-sun:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.type == masternode
          - node.hostname == sgp1-main-worker-sun

  masternode_moon:
    image: tomochain/node:devnet
    environment:
      IDENTITY: moon
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: true
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
      - netstats_ws_secret
    volumes:
      - masternode-moon:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.type == masternode
          - node.hostname == sgp1-main-worker-moon

  masternode_earth:
    image: tomochain/node:devnet
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      BOOTNODES: enode://5bec42d41c9eb291c1d20c9ac92bd9c86a4954189b6592b0833e5c28e389b59e3992efed119a2782d9b95ba7aa78e7f71813067cd6734fadff322f7dd6fc3b3c@104.248.99.234:30301,enode://89028bc15e9dda643bc4b9a1a6352896dd3bce7411543b0b160a9eb95093ddbe1f5eda5999e38a4874bfa6a00fb3526cc2fb9b4feb2a3f7cc80ef8016e05c493@104.248.99.235:30301,enode://ea8f1eb1a2a695960bfa6df52094c635e173c65e5fc120501672c0d21900d826d6c1c5a07d64ad36509ec5e7306d7a2c3398398f34f3e279b91c487c2b3a9537@104.248.99.233:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      ANNOUNCE_TXS: true
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 8546
        published: 8546
        protocol: tcp
        mode: host
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - masternode-earth:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.labels.type == masternode
          - node.hostname == sgp1-main-worker-earth

secrets:
  tomochain_password_sun:
    external: true
  tomochain_pk_sun:
    external: true
  tomochain_password_moon:
    external: true
  tomochain_pk_moon:
    external: true
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  masternode-sun:
  masternode-moon:
  masternode-earth:
