version: "3.4"

services:

  masternode_sun:
    image: tomochain/node:testnet
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      BOOTNODES: enode://f3d3d5d6cd0fdde8996722ff5b5a92f331029b2dcbdb9748f50db1421851a939eb660bf81a7ec7f359454aa0fd65fe4c03ae5c6bb2382b34dfaaca7eb6ecaf4e@52.77.194.164:30301,enode://34b923ddfcba1bfafdd1ac7a030436f9fbdc565919189f5e62c8cadd798c239b5807a26ab7f6b96a44200eb0399d1ebc2d9c1be94d2a774c8cc7660ff4c10367@13.228.93.232:30301,enode://e2604862d18049e025f294d63d537f9f54309ff09e45ed69ff4f18c984831f5ef45370053355301e3a4da95aba2698c6116f4d2a347e5a5e0a3152ac0ae0f574@18.136.42.72:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - masternode-sun:/tomochain/data

  masternode_moon:
    image: tomochain/node:testnet
    environment:
      IDENTITY: moon
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
      BOOTNODES: enode://f3d3d5d6cd0fdde8996722ff5b5a92f331029b2dcbdb9748f50db1421851a939eb660bf81a7ec7f359454aa0fd65fe4c03ae5c6bb2382b34dfaaca7eb6ecaf4e@52.77.194.164:30301,enode://34b923ddfcba1bfafdd1ac7a030436f9fbdc565919189f5e62c8cadd798c239b5807a26ab7f6b96a44200eb0399d1ebc2d9c1be94d2a774c8cc7660ff4c10367@13.228.93.232:30301,enode://e2604862d18049e025f294d63d537f9f54309ff09e45ed69ff4f18c984831f5ef45370053355301e3a4da95aba2698c6116f4d2a347e5a5e0a3152ac0ae0f574@18.136.42.72:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
      - netstats_ws_secret
    volumes:
      - masternode-moon:/tomochain/data

  masternode_earth:
    image: tomochain/node:testnet
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      BOOTNODES: enode://f3d3d5d6cd0fdde8996722ff5b5a92f331029b2dcbdb9748f50db1421851a939eb660bf81a7ec7f359454aa0fd65fe4c03ae5c6bb2382b34dfaaca7eb6ecaf4e@52.77.194.164:30301,enode://34b923ddfcba1bfafdd1ac7a030436f9fbdc565919189f5e62c8cadd798c239b5807a26ab7f6b96a44200eb0399d1ebc2d9c1be94d2a774c8cc7660ff4c10367@13.228.93.232:30301,enode://e2604862d18049e025f294d63d537f9f54309ff09e45ed69ff4f18c984831f5ef45370053355301e3a4da95aba2698c6116f4d2a347e5a5e0a3152ac0ae0f574@18.136.42.72:30301
      NETWORK_ID: 90
      VERBOSITY: 4
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - masternode-earth:/tomochain/data

secrets:
  tomochain_password_sun:
    external: true
  tomochain_pk_sun:
    external: true
  tomochain_password_moon:
    external: true
  tomochain_pk_moon:
    external: true
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  masternode-sun:
  masternode-moon:
  masternode-earth:
