version: "3.4"

services:

  netstats:
    image: tomochain/netstats:latest
    environment:
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret
    deploy:
      placement:
        constraints:
          - engine.labels.type == apps
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

secrets:
  netstats_ws_secret:
    external: true
