version: "3.4"

services:

  https-proxy:
    image: tomochain/nginx:latest
    ports:
      - 443:443
    volumes:
      - ./res/https-proxy/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - proxy_cert_pem
      - proxy_cert_private_key
    deploy:
      placement:
        constraints:
          - node.labels.role == proxy

secrets:
  proxy_cert_pem:
    external: true
  proxy_cert_private_key:
    external: true
