version: "3.4"

services:

  shepherd:
    image: mazzolino/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SLEEP_TIME: "5m"
    deploy:
      placement:
        constraints:
          - node.role == manager

  telegraf:
    image: tomochain/infra-telegraf:devnet
    hostname: moon.devnet.tomochain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  masternode_moon:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: moon
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      BOOTNODES: ''
    ports:
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
      - netstats_ws_secret
    volumes:
      - moon:/tomochain/data

secrets:
  tomochain_password_moon:
    external: true
  tomochain_pk_moon:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  moon:
