apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: influxdb
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  database: telegraf
  isDefault: true
  editable: false
  jsonData:
    timeInterval: '10s'
