version: "3.4"

services:

  masternode_earth:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      BOOTNODES: enode://11b2ca58233a95e03f44eee0d93f4076e84ed9f242e668b01db188d52d695319b782ffe55244f863093f5a6aa39189a7c301b007edbbf6a49e2bfcfbb7099f92@[10.0.0.8]:30301
      NETSTATS_HOST: http://52.220.195.222
      NETSTATS_PORT: 3000
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - earth:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  masternode_moon:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: moon
      PASSWORD_FILE: /run/secrets/tomochain_password_moon
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_moon
      BOOTNODES: enode://11b2ca58233a95e03f44eee0d93f4076e84ed9f242e668b01db188d52d695319b782ffe55244f863093f5a6aa39189a7c301b007edbbf6a49e2bfcfbb7099f92@[10.0.0.8]:30301
      NETSTATS_HOST: http://52.220.195.222
      NETSTATS_PORT: 3000
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - tomochain_password_moon
      - tomochain_pk_moon
      - netstats_ws_secret
    volumes:
      - moon:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  masternode_sun:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: sun
      PASSWORD_FILE: /run/secrets/tomochain_password_sun
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_sun
      BOOTNODES: enode://11b2ca58233a95e03f44eee0d93f4076e84ed9f242e668b01db188d52d695319b782ffe55244f863093f5a6aa39189a7c301b007edbbf6a49e2bfcfbb7099f92@[10.0.0.8]:30301
      NETSTATS_HOST: http://52.220.195.222
      NETSTATS_PORT: 3000
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    ports:
      - 8545:8545
      - 8546:8546
    secrets:
      - tomochain_password_sun
      - tomochain_pk_sun
      - netstats_ws_secret
    volumes:
      - sun:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  tomochain_password_moon:
    external: true
  tomochain_pk_moon:
    external: true
  tomochain_password_sun:
    external: true
  tomochain_pk_sun:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  earth:
  moon:
  sun:
