version: "3.4"

services:

  fullnode:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      BOOTNODES: enode://11b2ca58233a95e03f44eee0d93f4076e84ed9f242e668b01db188d52d695319b782ffe55244f863093f5a6aa39189a7c301b007edbbf6a49e2bfcfbb7099f92@[10.0.0.8]:30301
      NETSTATS_HOST: stats.testnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
    secrets:
      - netstats_ws_secret
    deploy:
      placement:
        constraints:
          - node.role != manager

secrets:
  netstats_ws_secret:
    external: true
