version: "3.4"

services:

  node:
    image: tomochain/node:stable
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    environment:
      IDENTITY: $IDENTITY
      PRIVATE_KEY: $PRIVATE_KEY
      BOOTNODES: enode://97f0ca95a653e3c44d5df2674e19e9324ea4bf4d47a46b1d8560f3ed4ea328f725acec3fcfcb37eb11706cf07da669e9688b091f1543f89b2425700a68bc8876@104.248.98.78:30301,enode://b72927f349f3a27b789d0ca615ffe3526f361665b496c80e7cc19dace78bd94785fdadc270054ab727dbb172d9e3113694600dd31b2558dd77ad85a869032dea@188.166.207.189:30301,enode://c8f2f0643527d4efffb8cb10ef9b6da4310c5ac9f2e988a7f85363e81d42f1793f64a9aa127dbaff56b1e8011f90fe9ff57fa02a36f73220da5ff81d8b8df351@104.248.98.60:30301
      NETWORK_ID: 88
      VERBOSITY: 3
      NETSTATS_HOST: stats.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET: getty-site-pablo-auger-room-sos-blair-shin-whiz-delhi
    volumes:
      - $DATA:/tomochain/data/tomo/chaindata
    networks:
      - masternode
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
    labels:
      - traefik.rpc.backend=rpc
      - traefik.rpc.frontend.rule=Host:rpc.tomochain.com
      - traefik.rpc.docker.network=masternode
      - traefik.rpc.port=8545
      - traefik.ws.backend=websocket
      - traefik.ws.frontend.rule=Host:ws.tomochain.com
      - traefik.ws.docker.network=masternode
      - traefik.ws.port=8546
      - traefik.ws.loadbalancer.stickiness=true
    restart: always

  proxy:
    image: traefik:alpine
    environment:
      CF_API_EMAIL: $CLOUDFLARE_EMAIL
      CF_API_KEY: $CLOUDFLARE_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./acme.json:/acme.json:rw
      - ./traefik.toml:/traefik.toml:ro
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - masternode
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=false

networks:
  masternode:
