{
 "title": "Services",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "services",
    "label": "Services",
    "query": "SHOW TAG VALUES WITH KEY = \"com.docker.swarm.service.name\""
   },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\" WHERE \"com.docker.swarm.service.name\" =~ /^$services$/"
   },
   {
    "name": "swarms",
    "label": "Swarms:",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\" WHERE \"com.docker.swarm.service.name\" =~ /^$services$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Services CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    }
   ]
  },
  {
   "title": "Services RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    }
   ]
  },
  {
   "title": "Services' containers CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    }
   ]
  },
  {
   "title": "Services RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    }
   ]
  },
  {
   "title": "Services' containers RX/TX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "down - [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    },
    {
     "alias": "up - [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "com.docker.swarm.service.name", "operator": "=~", "value": "/^$services$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/$swarms/" }
     ]
    }
   ]
  }
 ]
}