{
 "title": "Swarms",
 "description": "Swarms overview",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "swarms",
    "label": "Swarms:",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\""
   },
   {
    "name": "nodes",
    "label": "Nodes:",
    "query": "SHOW TAG VALUES WITH KEY = \"engine_host\" WHERE \"engine_host\" =~ /$swarms/"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Total CPU",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "vCPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Nodes Total RAM",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "Memory" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Nodes storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Stopped containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Paused containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nodes CPU",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Nodes RAM",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  }
 ]
}