version: "3.4"

services:

  bootnode:
    image: tomochain/infra-bootnode:devnet
    environment:
      VERBOSITY: 6
    ports:
      - 39391:39391
    volumes:
      - bootnodes:/tomochain
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  bootnodes:
