version: "3.4"

services:

  masternode_earth:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: earth
      PASSWORD_FILE: /run/secrets/tomochain_password_earth
      PRIVATE_KEY_FILE: /run/secrets/tomochain_pk_earth
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET_FILE: /run/secrets/netstats_ws_secret
      BOOTNODES: 'enode://f190d5fd9d71fab730ff0b58c2595a06abfed73de3fba180344b39da6f4605d0acbf91f00b0683f4b6a5a6d8515b64a1c288eadf78047b5ca1b3d6f090d3ec57@[10.0.14.8]:39391'
    ports:
      - target: 39393
        published: 39393
        mode: host
    secrets:
      - tomochain_password_earth
      - tomochain_pk_earth
      - netstats_ws_secret
    volumes:
      - earth:/tomochain/data
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.masternode == earth

secrets:
  tomochain_password_earth:
    external: true
  tomochain_pk_earth:
    external: true
  netstats_ws_secret:
    external: true

volumes:
  earth:
