version: "3.4"

services:

  fullnode:
    image: tomochain/infra-tomochain:devnet
    tty: true
    environment:
      IDENTITY: changeme
      BOOTNODES: changeme
      NETSTATS_HOST: stats.devnet.tomochain.com
      NETSTATS_PORT: 443
      WS_SECRET: changeme
    volumes:
      - blockchain:/tomochain/data

volumes:
  blockchain:
